# Generated by Django 3.2.19 on 2023-06-21 11:53

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_profiles_beds_alter_home_profiles_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_profiles',
            options={'verbose_name': 'home'},
        ),
        migrations.AlterField(
            model_name='home_profiles',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
